/*
 * api/purchase-api.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type PracticsCreatePurchaseResponse struct {
	Id string `json:"id,omitempty"`
	UserId string `json:"user_id,omitempty"`
	ItemId string `json:"item_id,omitempty"`
	PurchaseTime time.Time `json:"purchase_time,omitempty"`
}
