/*
 * api/purchase-api.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PracticsCreateUserRequest struct {

	Login string `json:"login,omitempty"`

	Password string `json:"password,omitempty"`

	Lastname string `json:"lastname,omitempty"`

	Firstname string `json:"firstname,omitempty"`
}
