/*
 * api/purchase-api.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"PurchaseApiServiceCreateItem",
		strings.ToUpper("Post"),
		"/v1/items",
		PurchaseApiServiceCreateItem,
	},

	Route{
		"PurchaseApiServiceCreatePurchase",
		strings.ToUpper("Post"),
		"/v1/purchase",
		PurchaseApiServiceCreatePurchase,
	},

	Route{
		"PurchaseApiServiceCreateUser",
		strings.ToUpper("Post"),
		"/v1/users",
		PurchaseApiServiceCreateUser,
	},

	Route{
		"PurchaseApiServiceDeletePurchase",
		strings.ToUpper("Delete"),
		"/v1/purchase/{id}",
		PurchaseApiServiceDeletePurchase,
	},

	Route{
		"PurchaseApiServiceGetPurchases",
		strings.ToUpper("Get"),
		"/v1/purchase",
		PurchaseApiServiceGetPurchases,
	},

	Route{
		"PurchaseApiServiceUpdateUser",
		strings.ToUpper("Put"),
		"/v1/users/{id}",
		PurchaseApiServiceUpdateUser,
	},
}
